name: despensaapp
description: App para la administración de la despensa.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2 #latest version
  kf_drawer: ^1.1.2
  generic_bloc_provider: ^1.0.9
  firebase_auth:
  google_sign_in:
  flutter_bloc:
    path: packages/flutter_bloc
  firebase_storage: ^2.1.0
  cloud_firestore: ^0.9.13
  equatable: ^0.2.0
  flutter_cupertino_date_picker: ^1.0.12
  image_picker_modern: ^0.4.12+2
  url_launcher:
  liquid_swipe: ^1.3.1
  jiffy: ^2.0.0
  google_maps_flutter: ^0.5.25
  geolocator: ^5.2.1
  provider: ^3.0.0
  http: ^0.12.0+4
  flutter_rating_bar: ^3.0.1+1
  stripe_payment: ^1.0.7
  progress_dialog: ^1.2.2
  flutter_credit_card: ^0.1.3
  # The following adds the ReactiveX package
  rxdart: ^0.22.0
  # The following adds the Swipper package
  flutter_swiper: ^1.1.4
  fl_chart: ^0.8.7
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.7
  flutter_dialogflow: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Gilroy-ExtraBold
      fonts:
        - asset: fonts/Gilroy-ExtraBold.otf
    - family: Gilroy-Light
      fonts:
        - asset: fonts/Gilroy-Light.otf
    - family: Poppins-Black
      fonts:
        - asset: fonts/Poppins-Black.otf
    - family: Poppins-BlackItalic
      fonts:
        - asset: fonts/Poppins-BlackItalic.otf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.otf
    - family: Poppins-BoldItalic
      fonts:
        - asset: fonts/Poppins-BoldItalic.otf
    - family: Poppins-ExtraBold
      fonts:
        - asset: fonts/Poppins-ExtraBold.otf
    - family: Poppins-ExtraBoldItalic
      fonts:
        - asset: fonts/Poppins-ExtraBoldItalic.otf
    - family: Poppins-ExtraLight
      fonts:
        - asset: fonts/Poppins-ExtraLight.otf
    - family: Poppins-Italic
      fonts:
        - asset: fonts/Poppins-Italic.otf
    - family: Poppins-Light
      fonts:
        - asset: fonts/Poppins-Light.otf
    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-Semibold.ttf
    - family: Poppins-Thin
      fonts:
        - asset: fonts/Poppins-Thin.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
  assets:
    - assets/images/logo.png
    - assets/images/Branding.png
    - assets/images/google_logo.png
    - assets/images/circle-outline-red.png
    - assets/images/1.png
    - assets/images/tienda-en-linea.png
    - assets/images/credito.png
    - assets/images/groceries.png
    - assets/images/store.png
    - assets/images/shopping-cart.png
    - assets/images/piggy-bank.png
    - assets/images/package.png
    - assets/images/discount.png
    - assets/images/qr-code.png
    - assets/images/online-store.png
    - assets/images/line-credit.png
    - assets/images/line-groceries.png
    - assets/images/line-store.png
    - assets/images/line-shopping-cart.png
    - assets/images/line-piggy-bank.png
    - assets/images/line-package.png
    - assets/images/line-discount.png
    - assets/images/line-qr-code.png
    - assets/images/line-truck.png
    - assets/images/line-list.png
    - assets/images/marker.png
    - assets/images/visa_logo.png
    - assets/images/creditcardchip.png
    - assets/images/card_band.jpg
    - assets/images/card_map.jpg
    - data/initial.json
    - assets/despensa-app-a9c63-f07727095d53.json
    - assets/images/person.png
    - assets/images/loader.gif
    - assets/images/happy-chatbot.gif